# Generated by Django 2.2.20 on 2021-05-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='SOME STRING2', max_length=20),
        ),
    ]
