# Generated by Django 2.2.20 on 2021-05-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketapp', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('Employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_name', models.CharField(max_length=30)),
                ('Employee_email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='SOME STRING2', max_length=20)),
            ],
        ),
    ]
