# Generated by Django 2.2.20 on 2021-05-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
