# Generated by Django 2.2.20 on 2021-05-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20210507_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
