# Generated by Django 2.2.20 on 2021-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_remove_employee_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='some string', max_length=30),
        ),
    ]
