# Generated by Django 2.2.20 on 2021-05-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0010_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
