# Generated by Django 2.2.20 on 2021-05-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0013_auto_20210508_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
