# Generated by Django 2.2.20 on 2021-05-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0030_auto_20210508_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
