# Generated by Django 2.2.20 on 2021-05-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0032_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
