# Generated by Django 2.2.20 on 2021-05-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0044_auto_20210510_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='user',
        ),
    ]
