# Generated by Django 2.2.20 on 2021-05-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0046_enduser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='user',
        ),
    ]
