# Generated by Django 2.2.20 on 2021-05-10 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketapp', '0047_remove_enduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='user',
            field=models.OneToOneField(default='string', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
